
name: Generate and push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME_DB: ${{secrets.NAME_DB}}
      USERNAME_DB: ${{secrets.USERNAME_DB}}
      PASSWORD_DB: ${{secrets.PASSWORD_DB}}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Static code analysis
        run: mvn spotbugs:check

      - name: Unit Tests and Generate coverage
        run: mvn clean verify -Dspotbugs.skip=true

      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'jacoco-report'
          path: target/site/jacoco

      - name: Code Build
        run: mvn clean install -DskipTests -Dspotbugs.skip=true

      - name: Generate Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/demo-app:${{github.sha}} .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKER_USERNAME}}/demo-app:${{github.sha}}
