
name: Generate and push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME_DB: jdbc:h2:file:./test
      USERNAME_DB: user2
      PASSWORD_DB: passw0rd2

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Static code analysis
        run: mvn spotbugs:check

      - name: Unit Tests and Generate coverage
        run: mvn clean verify
        continue-on-error: true

      - name: JaCoCo Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: '70'
          update-comment: 'true'
          title: 'Reporte cobertura de código'

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: 'jacoco-report'
          path: target/site/jacoco

      - name: Code Build
        if: ${{ failure() }}
        run: mvn clean install -DskipTests -Dspotbugs.skip=true
